apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockeragent-deployment-linux
  labels:
    app: dockeragent-deployment-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockeragent-linux
  template:
    metadata:
      labels:
        app: dockeragent-linux
      containers:
      - name: dockeragent-linux
        image: <ACRNAME>.azurecr.io/dockeragent/latest:latest
        ports:
        - containerPort: 80
        env:
        - name: AZP_URL
          value: "https://dev.azure.com/<ORGNAME>"
        - name: AZP_TOKEN
          value: PAT
        - name: AZP_AGENT_NAME
          value: demodockeragentlinux